# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170619_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='my_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='my_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='post.Comment'),
        ),
    ]
