# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=utils.fields.custom_imagefield.CustomImageField(blank=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
