# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170619_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
